# JITSI_15_USERS — Jicofo (live server + Jibri brewery)

jicofo {
    conference {
        max-participants = 15
        enable-auto-owner = true
        strip-simulcast = false
    }
    bridge {
        selection-strategy = SplitBridgeSelectionStrategy
        stress-threshold = 0.8
    }
}
