# JITSI_15_USERS — Video Bridge (live server əsaslı)

videobridge {
    cc {
        trust-bwe = true
        use-vla-target-bitrate = true
    }
    ice {
        udp {
            port = 10000
        }
        tcp {
            port = 4443
            enabled = true
        }
        advertise-private-addresses = false
    }
    stats {
        enabled = true
    }
    load {
        last-n = 20
    }
    sctp {
        enabled = true
    }
}
